### ISSUE TITLE
CloseCities hashcode is bad.

### ISSUE THREAD

**Issue by cohadar** [justradojko/CityDistances#6]
First of all: one is NOT a prime number.
There are two "kinds" of hashcode/equals you can define in a class.
First type is "all-fields-make-a-difference", this is how eclipse generates hashcode/equals.
(right-click inside a class) -> Source -> Generate hashcode/equals

Second type is "one-field-is-primary-key", you want a first city name to be a primary in your hashcode/equals, all other fields do not matter. This will remove all unwanted duplicates.

**Comment by justradojko** [comment]
If the requirement is that following outputs are considered as duplicates:

00:51 "Prairie" "Okolona"
00:47 "Okolona" "Prairie"

then, in my mind, hashCode should be constructed in a way that "primary key" is a function of both cities and not just one.
-  I'm also considering following output to be invalid:
  00:51 "Okolona" "Okolona"

Error that I could find in hashCode() function is that I was adding time.hashCode() into sum. Same stands for equals() function.

**Comment by justradojko** [comment]
In hashCode function var prime was set to 1 so I get the same hashCode value for objects (t, c1, c2) and (t, c2, c1). This will probably produce bad hashCode distribution between buckets, but since number of cities is 1000, percentage of duplicated hashCodes will be pretty low.

Code for hashCode() function was generated using Eclipse function, so I just replaced prime value 31 with 1. Leaving the same variable title was probably wrong thing.
